ALTER TABLE DROP EMPLOYEEID
DROP TABLE Orders;
DROP TABLE Food;
DROP TABLE Combo;
DROP TABLE ComboFood;
DROP TABLE Login;
DROP TABLE Employee;
DROP TABLE Card;
DROP TABLE Customer;
DROP TABLE FoodOrder;
DROP TABLE Location;
DROP TABLE Payment;