-- PROCEDURE USED TO INSERT NEW CUSTOMERS

CREATE OR REPLACE PROCEDURE SP_INSERT_NEW_CUSTOMER
(CUST_ID INT, F_NAME VARCHAR2,L_NAME VARCHAR2,EMAIL VARCHAR2, PHONE VARCHAR2, 
DOB DATE, PASS VARCHAR2, MOBILE VARCHAR2) AS
BEGIN
  INSERT INTO CUSTOMER(CUSTOMERID, FIRSTNAME,LASTNAME, EMAIL, PHONENUMBER,
  DATEOFBIRTH, DATEOFREGISTER, LASTLOGIN, PASS, MOBILE_NUMBER)
    VALUES(CUST_ID,F_NAME,L_NAME,EMAIL,PHONE,TO_DATE(DOB,'dd-MM-yyyy'),SYSTIMESTAMP,SYSTIMESTAMP,
    PASS, MOBILE);
END;
